import type { ComponentInfoItem } from "./component-info.types";

export const COMPONENT_INFO_MOCK_DATA: ComponentInfoItem[] = [
  {
    id: "BZ-BILSKNC300-0001",
    no: 998,
    componentId: "BZ-BILSKNC300-0001",
    componentName: "신용정보 연동",
    managerName: "박영수",
    managerOrg: "채권관리팀",
    systemCode: "SKNC300",
    businessName: "미납관리",
    createdBy: "홍길동",
    updatedBy: "이명숙",
    useYn: "사용",
    createdAt: "2026-02-18",
  },
  {
    id: "BZ-BILSKNC300-0002",
    no: 997,
    componentId: "BZ-BILSKNC300-0002",
    componentName: "미납관리대상 기준등록",
    managerName: "김지연",
    managerOrg: "채권관리팀",
    systemCode: "SKNC300",
    businessName: "미납관리",
    createdBy: "이순신",
    updatedBy: "김철수",
    useYn: "미사용",
    createdAt: "2025-12-22",
  },
  {
    id: "BZ-BILSKNC300-0003",
    no: 996,
    componentId: "BZ-BILSKNC300-0003",
    componentName: "미납원부 생성/배정",
    managerName: "이영희",
    managerOrg: "채권운영팀",
    systemCode: "SKNC300",
    businessName: "미납관리",
    createdBy: "강감찬",
    updatedBy: "이영희",
    useYn: "사용",
    createdAt: "2025-11-08",
  },
  {
    id: "BZ-BILSKNC300-0004",
    no: 995,
    componentId: "BZ-BILSKNC300-0004",
    componentName: "연체이자 계산",
    managerName: "장보라",
    managerOrg: "리스크관리팀",
    systemCode: "SKNC300",
    businessName: "미납관리",
    createdBy: "오세훈",
    updatedBy: "장보라",
    useYn: "사용",
    createdAt: "2025-10-15",
  },
  {
    id: "BZ-BILSKNC300-0005",
    no: 994,
    componentId: "BZ-BILSKNC300-0005",
    componentName: "채권추심 상태관리",
    managerName: "최민정",
    managerOrg: "채권운영팀",
    systemCode: "SKNC300",
    businessName: "미납관리",
    createdBy: "박철수",
    updatedBy: "최민정",
    useYn: "미사용",
    createdAt: "2025-08-21",
  },
];
