import type { CSSProperties } from "react";

const FONT_FAMILY = "'Pretendard', sans-serif";

export const typography = {
  title: {
    page: {
      fontFamily: FONT_FAMILY,
      fontSize: 32,
      fontWeight: 700,
      lineHeight: "40px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    popup: {
      fontFamily: FONT_FAMILY,
      fontSize: 24,
      fontWeight: 700,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  paragraphTitle: {
    xl: {
      fontFamily: FONT_FAMILY,
      fontSize: 20,
      fontWeight: 500,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    l: {
      fontFamily: FONT_FAMILY,
      fontSize: 18,
      fontWeight: 700,
      lineHeight: "28px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    m: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 700,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    s: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 700,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    xs: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 700,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  paragraph: {
    xl: {
      fontFamily: FONT_FAMILY,
      fontSize: 20,
      fontWeight: 400,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    l: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    m: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 400,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    s: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 400,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    xs: {
      fontFamily: FONT_FAMILY,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: "16px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  field: {
    labelM: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    labelS: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 500,
      lineHeight: "16px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    valueL: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    valueM: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    indicator: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 400,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    placeholderL: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },
};

export const FONT = FONT_FAMILY;

export const listStyles = {
  outer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minHeight: "100%",
    fontFamily: FONT_FAMILY,
  } satisfies CSSProperties,
  main: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: 32,
    flex: 1,
  } satisfies CSSProperties,
  filterWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "16px 24px",
    borderRadius: 8,
    backgroundColor: "#ffffff",
  } satisfies CSSProperties,
  listWrap: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  } satisfies CSSProperties,
  tableFunction: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  } satisfies CSSProperties,
  tableFuncLeft: {
    display: "flex",
    alignItems: "center",
    gap: 32,
  } satisfies CSSProperties,
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #d4d4d8",
    backgroundColor: "#fafafa",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#52525b",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  listAction: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    paddingBottom: 8,
  } satisfies CSSProperties,
  paginationField: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  paginationLabel: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  itemsSelect: {
    height: 40,
    padding: "3px 4px",
    border: "1px solid #e4e7ec",
    borderRadius: 4,
    backgroundColor: "white",
    fontSize: 14,
    lineHeight: "20px",
    color: "#3f3f46",
    cursor: "pointer",
    boxSizing: "border-box",
    outline: "none",
  } satisfies CSSProperties,
  indicator: {
    fontSize: 14,
    lineHeight: "20px",
    color: "#71717a",
    textAlign: "center",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  paginationWrap: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  } satisfies CSSProperties,
  pageBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    borderRadius: 4,
  } satisfies CSSProperties,
  pageBtnActive: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#111827",
    padding: "0 6px",
    opacity: 1,
  } satisfies CSSProperties,
  pageBtnInactive: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#71717a",
    padding: "0 6px",
    opacity: 0.4,
  } satisfies CSSProperties,
  downloadBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    borderRadius: 4,
  } satisfies CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    border: "1px solid #e4e4e7",
    borderRadius: 4,
    overflow: "hidden",
    tableLayout: "fixed",
    backgroundColor: "#ffffff",
  } satisfies CSSProperties,
  th: {
    backgroundColor: "#f4f4f5",
    border: "1px solid #e4e4e7",
    padding: 8,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#000000",
    textAlign: "center",
    whiteSpace: "nowrap",
    minHeight: 36,
    boxSizing: "border-box",
    cursor: "pointer",
  } satisfies CSSProperties,
  thInner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: "100%",
  } satisfies CSSProperties,
  td: {
    backgroundColor: "white",
    border: "1px solid #e4e4e7",
    padding: 8,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#000000",
    textAlign: "center",
    minHeight: 40,
    boxSizing: "border-box",
    verticalAlign: "middle",
  } satisfies CSSProperties,
  tdLeft: {
    textAlign: "left",
  } satisfies CSSProperties,
  useBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #7a5af8",
    backgroundColor: "#fafaff",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7a5af8",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  unuseBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #a1a1aa",
    backgroundColor: "#fafafa",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
} as const;
