import type { CSSProperties } from "react";

const FONT_FAMILY = "'Pretendard', sans-serif";

export const typography = {
  title: {
    page: {
      fontFamily: FONT_FAMILY,
      fontSize: 32,
      fontWeight: 700,
      lineHeight: "40px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    popup: {
      fontFamily: FONT_FAMILY,
      fontSize: 24,
      fontWeight: 700,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  paragraphTitle: {
    xl: {
      fontFamily: FONT_FAMILY,
      fontSize: 20,
      fontWeight: 500,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    l: {
      fontFamily: FONT_FAMILY,
      fontSize: 18,
      fontWeight: 700,
      lineHeight: "28px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    m: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 700,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    s: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 700,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    xs: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 700,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  paragraph: {
    xl: {
      fontFamily: FONT_FAMILY,
      fontSize: 20,
      fontWeight: 400,
      lineHeight: "32px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    l: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    m: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 400,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    s: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 400,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    xs: {
      fontFamily: FONT_FAMILY,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: "16px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },

  field: {
    labelM: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    labelS: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 500,
      lineHeight: "16px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    valueL: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    valueM: {
      fontFamily: FONT_FAMILY,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "20px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    indicator: {
      fontFamily: FONT_FAMILY,
      fontSize: 12,
      fontWeight: 400,
      lineHeight: "18px",
      fontStyle: "normal",
    } satisfies CSSProperties,
    placeholderL: {
      fontFamily: FONT_FAMILY,
      fontSize: 16,
      fontWeight: 400,
      lineHeight: "24px",
      fontStyle: "normal",
    } satisfies CSSProperties,
  },
};

export const FONT = FONT_FAMILY;

export const listStyles = {
  outer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minHeight: "100%",
    fontFamily: FONT_FAMILY,
  } satisfies CSSProperties,
  main: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: 32,
    flex: 1,
  } satisfies CSSProperties,
  filterWrap: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "16px 24px",
    backgroundColor: "#f8f9fc",
    borderRadius: 8,
  } satisfies CSSProperties,
  listWrap: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
  } satisfies CSSProperties,
  tableFunction: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  } satisfies CSSProperties,
  tableFuncLeft: {
    display: "flex",
    alignItems: "center",
    gap: 32,
  } satisfies CSSProperties,
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #71717a",
    backgroundColor: "#fafafa",
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#71717a",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  listAction: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    paddingBottom: 8,
  } satisfies CSSProperties,
  paginationField: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  paginationLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  itemsSelect: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    height: 40,
    padding: "3px 4px",
    border: "1px solid #e4e7ec",
    borderRadius: 4,
    backgroundColor: "white",
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#3f3f46",
    cursor: "pointer",
    boxSizing: "border-box",
    outline: "none",
  } satisfies CSSProperties,
  indicator: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#71717a",
    textAlign: "center",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  paginationWrap: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  } satisfies CSSProperties,
  pageBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    borderRadius: 4,
  } satisfies CSSProperties,
  pageBtnActive: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#71717a",
    padding: "0 6px",
    opacity: 1,
  } satisfies CSSProperties,
  pageBtnInactive: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#71717a",
    padding: "0 6px",
    opacity: 0.4,
  } satisfies CSSProperties,
  downloadBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    borderRadius: 4,
  } satisfies CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    border: "1px solid #e4e4e7",
    overflow: "hidden",
    tableLayout: "fixed",
  } satisfies CSSProperties,
  th: {
    backgroundColor: "#f4f4f5",
    border: "1px solid #e4e4e7",
    padding: 8,
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "black",
    textAlign: "center",
    whiteSpace: "nowrap",
    minHeight: 36,
    boxSizing: "border-box",
  } satisfies CSSProperties,
  thInner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: "100%",
  } satisfies CSSProperties,
  td: {
    backgroundColor: "white",
    border: "1px solid #e4e4e7",
    padding: 8,
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "black",
    textAlign: "center",
    minHeight: 40,
    boxSizing: "border-box",
    verticalAlign: "middle",
  } satisfies CSSProperties,
  tdLeft: {
    textAlign: "left",
  } satisfies CSSProperties,
  useBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #7a5af8",
    backgroundColor: "#fafaff",
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7a5af8",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  unuseBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 12px",
    borderRadius: 12,
    border: "1px solid #a1a1aa",
    backgroundColor: "#fafafa",
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
};

export const detailStyles = {
  outer: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minHeight: "100%",
    fontFamily: FONT_FAMILY,
  } satisfies CSSProperties,
  main: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
    padding: 32,
    flex: 1,
  } satisfies CSSProperties,
  contentWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 32,
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 32,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  metaItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  metaLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: 10,
    fontWeight: 400,
    lineHeight: "16px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  metaValue: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#3f3f46",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  categoryBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2px 8px",
    borderRadius: 4,
    fontFamily: FONT_FAMILY,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  contentSection: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  contentLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    color: "#a1a1aa",
  } satisfies CSSProperties,
  contentBody: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "22px",
    color: "#3f3f46",
    whiteSpace: "pre-wrap",
    minHeight: 100,
    padding: "12px 0",
  } satisfies CSSProperties,
  attachSection: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  attachLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    color: "#a1a1aa",
  } satisfies CSSProperties,
  fileList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  fileItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minHeight: 40,
    padding: "8px 12px 8px 8px",
    backgroundColor: "#ffffff",
    border: "1px solid #e4e4e7",
    borderRadius: 4,
    boxSizing: "border-box",
    cursor: "pointer",
  } satisfies CSSProperties,
  fileNameWrap: {
    display: "flex",
    flex: 1,
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  } satisfies CSSProperties,
  fileName: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#3f3f46",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  } satisfies CSSProperties,
  fileMeta: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
  } satisfies CSSProperties,
  fileMetaItem: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  } satisfies CSSProperties,
  fileMetaLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: 10,
    fontWeight: 400,
    lineHeight: "16px",
    color: "#a1a1aa",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fileMetaValue: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#3f3f46",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  btnRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  } satisfies CSSProperties,
  btnLeft: {
    display: "flex",
    alignItems: "center",
    flex: 1,
  } satisfies CSSProperties,
  btnRight: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexShrink: 0,
  } satisfies CSSProperties,
};

export const popupStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  } satisfies CSSProperties,
  popup: {
    width: 880,
    maxHeight: "90vh",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.12)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    fontFamily: FONT_FAMILY,
  } satisfies CSSProperties,
  header: {
    padding: "32px 32px 16px",
    flexShrink: 0,
  } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  } satisfies CSSProperties,
  titleText: {
    fontFamily: FONT_FAMILY,
    fontSize: 24,
    fontWeight: 700,
    lineHeight: "32px",
    color: "#18181b",
  } satisfies CSSProperties,
  closeBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    borderRadius: 4,
  } satisfies CSSProperties,
  requiredRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  requiredDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    backgroundColor: "#36bffa",
    flexShrink: 0,
  } satisfies CSSProperties,
  requiredText: {
    fontFamily: FONT_FAMILY,
    fontSize: 12,
    fontWeight: 400,
    lineHeight: "18px",
    color: "#a1a1aa",
  } satisfies CSSProperties,
  main: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 32px 32px",
  } satisfies CSSProperties,
  formSection: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  fieldLabel: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  } satisfies CSSProperties,
  labelText: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    color: "#52525b",
  } satisfies CSSProperties,
  fieldRow: {
    display: "flex",
    gap: 32,
  } satisfies CSSProperties,
  uploadArea: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 120,
    border: "1px dashed #e4e7ec",
    borderRadius: 8,
    backgroundColor: "#fafafa",
    cursor: "pointer",
    padding: 24,
    transition: "border-color 0.15s, background-color 0.15s",
  } satisfies CSSProperties,
  uploadAreaDragging: {
    border: "2px dashed #7a5af8",
    backgroundColor: "#f5f3ff",
  } satisfies CSSProperties,
  uploadText: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#a1a1aa",
    textAlign: "center",
  } satisfies CSSProperties,
  uploadBtn: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#7a5af8",
    cursor: "pointer",
    textDecoration: "underline",
    background: "none",
    border: "none",
    padding: 0,
  } satisfies CSSProperties,
  fileList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    marginTop: 8,
  } satisfies CSSProperties,
  fileItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    backgroundColor: "#f4f4f5",
    borderRadius: 4,
  } satisfies CSSProperties,
  fileName: {
    fontFamily: FONT_FAMILY,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    color: "#3f3f46",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  fileDeleteBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 32px 24px",
    flexShrink: 0,
    borderTop: "1px solid #f4f4f5",
  } satisfies CSSProperties,
  footerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  footerRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
};
